### ISSUE TITLE
`Bug`: TLS timeout

### ISSUE THREAD

**Issue by pmcastillo-glitch** [gyptazy/ProxLB#389]
## General
I have been running ProxLB for 3 weeks in a Clusters and suddenly I am getting this error. 

2025-12-09 04:42:33,326 - ProxLB - DEBUG - Finished: get_nodes.
Dec 09 04:42:33 proxlb01.dal09.int.jepphost.com ProxLB[1440]: 2025-12-09 04:42:33,326 - ProxLB - DEBUG - Starting: get_pools.
Dec 09 04:42:33 proxlb01.dal09.int.jepphost.com ProxLB[1440]: 2025-12-09 04:42:33,330 - ProxLB - DEBUG - Finished: get_pools.
Dec 09 04:42:33 proxlb01.dal09.int.jepphost.com ProxLB[1440]: 2025-12-09 04:42:33,330 - ProxLB - DEBUG - Starting: get_guests.
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]: Traceback (most recent call last):
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:   File "/usr/lib/python3/dist-packages/proxlb/main.py", line 114, in <module>
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:     main()
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:   File "/usr/lib/python3/dist-packages/proxlb/main.py", line 77, in main
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:     guests = Guests.get_guests(proxmox_api, pools, nodes, meta, proxlb_config)
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:   File "/usr/lib/python3/dist-packages/proxlb/models/guests.py", line 66, in get_guests
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:     for guest in proxmox_api.nodes(node).qemu.get():
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:   File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 169, in get
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:     return self(args)._request("GET", params=params)
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:   File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 149, in _request
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]:     raise ResourceException(
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com python3[1440]: proxmoxer.core.ResourceException: 596 Errors during TLS negotiation, request sending and header processing: Connection timed out - {'errors': b''}
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com systemd[1]: proxlb.service: Main process exited, code=exited, status=1/FAILURE
Dec 09 04:43:04 proxlb01.dal09.int.jepphost.com systemd[1]: proxlb.service: Failed with result 'exit-code'.

**Comment by gyptazy** [comment]
Hey @pmcastillo-glitch,

thanks for your report. As you said, you already had this running for weeks and this error raises when connecting to the API `proxmoxer.core.ResourceException: 596 Errors during TLS negotiation`, I can currently only assume an issue on the network and/or Proxmox VE site. Did this occur only a single time or always? What happens if you switch the API node?

Cheers,
gyptazy

**Comment by pmcastillo-glitch** [comment]
All  6 seems to be returning the same at the moment.

**Comment by pmcastillo-glitch** [comment]
Thanks for the help man, sorry I did no reply quicker but I have been busy. So I fixed the problem by rebooting two of the nodes, both nodes were timing out (error 596) just when querying https://HOSTNAME:8006/api2/json/nodes/NODE/qemu. 

I tried to restart pveproxy but that did not help and I was not sure what are the consequences of restarting the qemu.slice process with live VMs so I went for a reboot.

**Comment by akballow** [comment]
What i have been noticing is after restarting multiple times sometimes it progresses, but eventually it fails with the same message. Is there anything that can be configured to allow more retries? The retries: in proxmox_api seems to make no difference.

**Comment by gyptazy** [comment]
Hey @akballow,

I don't think this is a bug related to ProxLB. We can also clearly see within the logs that this issue gets raised from the underlying lib for the API orchestration, which runs into timeouts when communicating with the Proxmox API.

While adding retries and increasing timeouts could work, this doesn't really fix the underlying issues which are located within the Proxmox cluster. This can often have different reasons like higher loads on the nodes (keep in mind, that all nodes are included to obtain the data), but also architectural design can matter (like Corosync usage, etc.).

As said before, keep in mind, that all nodes will be included to gather the data - not only the node, that you're talking to the API. Maybe any other node has higher pressure which results into those timeouts.

Cheers,
gyptazy

**Comment by akballow** [comment]
@gyptazy thanks for the input. I have checked everything you mentioned and nothing seems out of the normal. Latency between all my nodes are under 0.1, corosync is happy without any errors in any logs. There is no pressure on anything as these are some really beefy servers 96 core 2TB memory with 25G nics.

By any chance is it just because I am working with over 1000 VMs and the tool itself times out waiting for all the api calls?

my next attempt is hardcoding a larger, from 30, to 120 second api http timeout.

But to ask a question to you, I do not see the fields below in your tool making any difference. Would these not change the behavior that this ticket is about. 
  timeout: #
  retries: #
  wait_time: #

**Comment by gyptazy** [comment]
Keep in mind that changes are not persistent over upgrades and those could overwrite the changes (if that file gets updated by upstream). But it would be great to know if it is related to this (but it would make sense because it failed during the guest evaluation which is exactly the slot of gathering the pressure based values).

**Comment by gyptazy** [comment]
@akballow awesome! Thanks a lot for testing, validating and pointing this out! Guess, that helps other ones a lot!

Let’s see how this can become adjusted in Proxmox upstream. Larger clusters might frequently run into this issue when simply getting a list of guests (which includes pressure metrics with PVE9).
